name: Pull Requests

on:
  pull_request:
    types: [ opened, synchronize ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull Request Validator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
